# Integer Encoding SimpleRNN Practice

In [2]:
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, Embedding,Flatten

In [2]:
(x_train,y_train),(x_test,y_test) =imdb.load_data()

17464789/17464789 [==============================] - 76s 4us/step


In [3]:
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((25000,), (25000,), (25000,), (25000,))

In [11]:
len(x_train[5])

2494

In [13]:
len(x_test[5])

2315

In [12]:
x_train[1]

array([   1,  194, 1153, ...,    0,    0,    0])

In [7]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
x_train = pad_sequences(x_train, padding='post',maxlen=500)
x_test = pad_sequences(x_test, padding='post',maxlen=500)

In [ ]:
model =Sequential()
model.add(SimpleRNN(32, input_shape=(x_train.shape[1], 1), return_sequences=True))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))


In [16]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 500, 32)           1088      
                                                                 
 simple_rnn_3 (SimpleRNN)    (None, 32)                2080      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 3,201
Trainable params: 3,201
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.fit(x_train, y_train, epochs=5, batch_size=64, validation_data=(x_test, y_test))

Epoch 1/5
391/391 [==============================] - 110s 276ms/step - loss: 0.6963 - accuracy: 0.5039 - val_loss: 0.7013 - val_accuracy: 0.5000
Epoch 2/5
391/391 [==============================] - 98s 251ms/step - loss: 0.6973 - accuracy: 0.4978 - val_loss: 0.6934 - val_accuracy: 0.5000
Epoch 3/5
391/391 [==============================] - 96s 246ms/step - loss: 0.6959 - accuracy: 0.4990 - val_loss: 0.6949 - val_accuracy: 0.4999
Epoch 4/5
391/391 [==============================] - 100s 255ms/step - loss: 0.6975 - accuracy: 0.4960 - val_loss: 0.6956 - val_accuracy: 0.5000
Epoch 5/5
391/391 [==============================] - 103s 265ms/step - loss: 0.6971 - accuracy: 0.5016 - val_loss: 0.6988 - val_accuracy: 0.5000


In [18]:
loss, accuracy = model.evaluate(x_test, y_test)

782/782 [==============================] - 46s 59ms/step - loss: 0.6988 - accuracy: 0.5000


# Embedding SimpleRNN Practice

In [1]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [2]:
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=10000)

In [3]:
print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(25000,) (25000,)
(25000,) (25000,)


In [4]:
# Pad sequences
x_train = pad_sequences(x_train, padding='post', maxlen=500)
x_test = pad_sequences(x_test, padding='post', maxlen=500)

In [5]:
# Convert labels
y_train = np.array(y_train)
y_test = np.array(y_test)


In [6]:
y_train ,y_test

(array([1, 0, 0, ..., 0, 1, 0], dtype=int64),
 array([0, 1, 1, ..., 0, 0, 0], dtype=int64))

In [7]:
y_train = np.array(y_train)
y_test = np.array(y_test)

In [8]:
# Build model
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2, input_length=500))
model.add(SimpleRNN(32))
model.add(Dense(1, activation='sigmoid'))

In [9]:
# Compile and train
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 500, 2)            20000     
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                1120      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 21,153
Trainable params: 21,153
Non-trainable params: 0
_________________________________________________________________


In [10]:
history = model.fit(x_train, y_train, epochs=5, batch_size=64, validation_data=(x_test, y_test))

Epoch 1/5
391/391 [==============================] - 59s 148ms/step - loss: 0.6943 - accuracy: 0.5017 - val_loss: 0.6962 - val_accuracy: 0.5004
Epoch 2/5
391/391 [==============================] - 53s 136ms/step - loss: 0.6931 - accuracy: 0.5054 - val_loss: 0.6928 - val_accuracy: 0.5137
Epoch 3/5
391/391 [==============================] - 57s 145ms/step - loss: 0.6946 - accuracy: 0.5026 - val_loss: 0.6936 - val_accuracy: 0.5020
Epoch 4/5
391/391 [==============================] - 58s 148ms/step - loss: 0.6945 - accuracy: 0.5042 - val_loss: 0.6938 - val_accuracy: 0.5023
Epoch 5/5
391/391 [==============================] - 73s 187ms/step - loss: 0.6939 - accuracy: 0.4978 - val_loss: 0.6955 - val_accuracy: 0.5000


In [11]:
# Evaluate
loss, accuracy = model.evaluate(x_test, y_test)
print(f"Test Loss: {loss:.4f}, Test Accuracy: {accuracy:.4f}")

782/782 [==============================] - 20s 25ms/step - loss: 0.6955 - accuracy: 0.5000
Test Loss: 0.6955, Test Accuracy: 0.5000
